/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UwamRouteImport } from './routes/uwam'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as IndexRouteImport } from './routes/index'

const UwamRoute = UwamRouteImport.update({
  id: '/uwam',
  path: '/uwam',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/ecosystem': typeof EcosystemRoute
  '/financials': typeof FinancialsRoute
  '/invest': typeof InvestRoute
  '/uwam': typeof UwamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/ecosystem': typeof EcosystemRoute
  '/financials': typeof FinancialsRoute
  '/invest': typeof InvestRoute
  '/uwam': typeof UwamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/ecosystem': typeof EcosystemRoute
  '/financials': typeof FinancialsRoute
  '/invest': typeof InvestRoute
  '/uwam': typeof UwamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/dashboard'
    | '/demo'
    | '/ecosystem'
    | '/financials'
    | '/invest'
    | '/uwam'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm'
    | '/dashboard'
    | '/demo'
    | '/ecosystem'
    | '/financials'
    | '/invest'
    | '/uwam'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/dashboard'
    | '/demo'
    | '/ecosystem'
    | '/financials'
    | '/invest'
    | '/uwam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  EcosystemRoute: typeof EcosystemRoute
  FinancialsRoute: typeof FinancialsRoute
  InvestRoute: typeof InvestRoute
  UwamRoute: typeof UwamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uwam': {
      id: '/uwam'
      path: '/uwam'
      fullPath: '/uwam'
      preLoaderRoute: typeof UwamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  EcosystemRoute: EcosystemRoute,
  FinancialsRoute: FinancialsRoute,
  InvestRoute: InvestRoute,
  UwamRoute: UwamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
